#!/bin/bash
#-------------------------------------------------------------#
# this first part is mostly taken from debian and kubuntu
#-------------------------------------------------------------#

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines in the history. See bash(1) for more options
# don't overwrite GNU Midnight Commander's setting of `ignorespace'.
HISTCONTROL=$HISTCONTROL${HISTCONTROL+:}ignoredups
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -lA'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

#-------------------------------------------------------------#
# the rest of this is my own custom stuff
#-------------------------------------------------------------#

# prompt should always be in color for readability.
# if the term doesn't support color then i'd just use a different terminal. :)
CSI='\[\033['; BOLD="01";  FG='3'; END="m\]"
k='0'; r='1'; g='2'; y='3'; b='4'; m='5'; c='6'; w='7'

RESET="${CSI}0$END"
GRAY="$CSI$BOLD;$FG$k$END"
WHITE="$CSI$BOLD;$FG$w$END"
GREEN="$CSI$BOLD;$FG$g$END"
BLUE="$CSI$BOLD;$FG$b$END"
CYAN="$CSI$BOLD;$FG$c$END"
DKRED="$RESET$CSI$FG$r$END"
BRRED="$CSI$BOLD;$FG$r$END"
MGNTA="$CSI$BOLD;$FG$m$END"
YELLO="$CSI$BOLD;$FG$y$END"
WORKD="\w"
PS1="$MGNTA:`hostname`:$DKRED$WORKD$RESET\$ "


export LANG=en_US.UTF-8
# without this, you get weird box drawing characters
# basically it tells ncurses to use unicode characters
# rather than an (a)lternate (c)haracter (s)et
if [ "$TERM" == 'xterm-256color' ] || [ "$TERM" == 'screen-256color' ]; then
  export NCURSES_NO_UTF8_ACS=1
else
  #setfont silverware/other/sabren.fnt
  unicode_start
fi

# force tmux to use 256 color support:
alias tmux="tmux -2"

# git helpers
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gf='git fetch'
alias gp='git push'
alias gs='git status'
alias gh='git checkout'
alias gr='git remote'
# thanks to raylu for this one.
alias gl='git log --graph --abbrev-commit --stat -C --decorate --date=local'
gsa() { # (g)it (s)tatus for (a)ll subdirectiores
  find -maxdepth 2 -name .git \
       -exec sh -c 'echo {} | sed "s/^[.][/]\(.*\)[/][.]git$/* \1/"' \; \
       -execdir git status -s \;
}

# show the path
path() {
   echo $PATH | tr : '\n' | uniq
}

# normal path:
export PATH=$PATH:/bin:/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
export LD_LIBRARY_PATH=/usr/local/lib

# use local stuff instead of system's version
# ( for testing custom versions, etc )
export PATH=~/bin:~/t/bin:$PATH

# use emacsclient to allow sharing buffers between windows
# the symlink ~/bin/emacs controls which version of emacs actually runs.
mkdir -p ~/bin
if [ "$OS" != "Windows_NT" ]
then
  if [ ! -e ~/bin/emacs ] ; then  ln -s `which emacs` ~/bin/emacs ; fi
  alias emacs='emacsclient -nw --alternate-editor ~/bin/emacs'
fi

# xd to change directories
xd() {
 cd `/usr/bin/xd $*`
}

# grun for antlr4
export CLASSPATH=".:/home/michal/jar/antlr-4.0-complete.jar:$CLASSPATH"
alias antlr4='java -jar ~/jar/antlr-4.0-complete.jar'
alias grun='java org.antlr.v4.runtime.misc.TestRig'

# machine-specific stuff
LOCALBASH=~/ver/tangentconf/bash/$USER@$HOSTNAME.bash
if [ -f $LOCALBASH ]; then . $LOCALBASH ; fi

export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

export PATH="/Library/Developer/CommandLineTools/usr/bin:$PATH"

if [ -e ~/.cargo/env ]; then source ~/.cargo/env; fi

# Created by `pipx` on 2022-06-29 20:47:20
export PATH="$PATH:/home/michal/.local/bin"

export PATH=$PATH:~/tmp/go/bin

[ -f "/home/michal/.ghcup/env" ] && source "/home/michal/.ghcup/env" # ghcup-env
