#!/bin/bash
#-------------------------------------------------------------#
# this first part is mostly taken from debian and kubuntu
#-------------------------------------------------------------#

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines in the history. See bash(1) for more options
# don't overwrite GNU Midnight Commander's setting of `ignorespace'.
HISTCONTROL=$HISTCONTROL${HISTCONTROL+:}ignoredups
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -lA'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

#-------------------------------------------------------------#
# the rest of this is my own custom stuff
#-------------------------------------------------------------#


# prompt should always be in color for readability.
# if the term doesn't support color then i'd just use a different terminal. :)
CSI='\[\033['; BOLD="01";  FG='3'; END="m\]"
k='0'; r='1'; g='2'; y='3'; b='4'; m='5'; c='6'; w='7'

RESET="${CSI}0$END"
GRAY="$CSI$BOLD;$FG$k$END"
WHITE="$CSI$BOLD;$FG$w$END"
GREEN="$CSI$BOLD;$FG$g$END"
BLUE="$CSI$BOLD;$FG$b$END"
CYAN="$CSI$BOLD;$FG$c$END"
DKRED="$RESET$CSI$FG$r$END"
BRRED="$CSI$BOLD;$FG$r$END"
WORKD="\w"
PS1="$GREEN\u@\h$RESET:$BLUE$WORKD$RESET\$ "

# without this, you get weird box drawing characters
# basically it tells ncurses to use unicode characters
# rather than an (a)lternate (c)haracter (s)et
if [ "$TERM" == 'xterm-256color' ] || [ "$TERM" == 'screen-256color' ]; then
  export NCURSES_NO_UTF8_ACS=1
else
  #setfont silverware/other/sabren.fnt
  unicode_start
fi

# force tmux to use 256 color support:
alias tmux="tmux -2"

# git helpers
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gf='git fetch'
alias gp='git push'
alias gs='git status'
alias gu='git submodule update'

# prevent emacs from going into x mode,
# and allow sharing buffers between windows
alias emacs='emacsclient -nw'

# use local stuff instead of system's version
# ( for testing custom versions, etc )
export PATH=~/bin:/usr/local/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/lib

# machine-specific stuff
LOCALBASH=~/ver/tangentconf/bash/$USER@$HOSTNAME.bash
if [ -f $LOCALBASH ]; then . $LOCALBASH ; fi
