# this one only executes for login shells

if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/michal.wallace/.sdkman"
[[ -s "/Users/michal.wallace/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/michal.wallace/.sdkman/bin/sdkman-init.sh"

export PATH="$HOME/.cargo/bin:$PATH"

# Setting PATH for Python 3.7
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin:${PATH}"
export PATH

# for lean4:
export PATH="$HOME/.elan/bin:$PATH"

# Created by `pipx` on 2022-06-29 20:47:20
export PATH="$PATH:/home/michal/.local/bin"
