# this one only executes for login shells

if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi

export PATH="$HOME/.cargo/bin:$PATH"

# for lean4:
export PATH="$HOME/.elan/bin:$PATH"

# Created by `pipx` on 2022-06-29 20:47:20
export PATH="$PATH:/home/michal/.local/bin"
